### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Redunda#52] opened 2018-11-15 17:38 UTC
https://redunda.sobotics.org/authentication/login_redirect_target?code=xxxxxxxxxxxxxx

Logging in results in this error:
>No such file or directory @ rb_sysopen - https://api.stackexchange.com/2.2/access-tokens/yyyyyyyyy?key=xxxxxxxxxxx
>Extracted source (around line #37):
> ```
> def info_for_access_token(access_token)
>     config = AppConfig["stack_exchange"]
>     JSON.parse(open("https://api.stackexchange.com/2.2/access-tokens/#{access_token}?key=#{config["key"]}").read)["items"][0]
>   end
> 
> def username_for_access_token(access_token)
> ```

Tested with Chrome and Firefox on Windows

**Comment by fortunate-man** [comment] 2018-11-16 11:46
Reproduced with Firefox on macOS Mojave.

**Comment by fortunate-man** [comment] 2018-11-16 11:50
This seems to be the problem: https://stackoverflow.com/questions/4952522/error-when-trying-to-open-a-url-in-ruby-on-rails

**Comment by fortunate-man** [comment] 2018-11-16 12:04
This might help: https://stackoverflow.com/questions/4952522/error-when-trying-to-open-a-url-in-ruby-on-rails

**Comment by Undo1** [comment] 2018-12-13 15:36
Should be fixed in https://github.com/SOBotics/Redunda/commit/2415347c8b53e5321abb34b0b4802786a6be2624

**Closed by Undo1** 2018-12-13 15:36 UTC
Labels: type: bug

**Comment by fortunate-man** [comment] 2018-12-14 11:58
Seems to work for me @Undo1, thanks!

**Comment by Filnor** [comment] 2018-12-14 12:10
For me too.
